---
version: 1.0
root: "./.tests/cloud_test_calico/"
timeout: 7200  # 2 hour total total timeout
shuffle-enabled: true
statistics:
  enabled: true
  interval: 60  # 60 seconds for statistics
import:
  - cloudtest/packet.yaml
  - cloudtest/tests.yaml

retest:  # Allow to do test re-run if some kind of failures are detected.
  count: 2  # Allow 2 times to do restart
  pattern:
    - "rx 0 pong packets"    # Error in VFIO tests
reporting:
  junit-report: "results/junit.xml"
health-check:
  - message: "Branch is not up to date"
    interval: 60  # 1 minute
    run: |
      echo "Health check!"
